### PR TITLE
Updates to Project Dependencies

### PR DESCRIPTION
**Pull request by eefei22**
# Issues to Address
### **Outdated Dependencies**
- The project was dependent on an older version of Electron `13.0.0`, which may lack recent performance improvements, security updates, and features.

### **Lack of Support for Native Module Compilation**
- The project lacked explicit support for compiling native addons, which will affect the functionality in newer Electron environments.

### **Inconsistent Dependency Usage**
- The `electron-rebuild` package was only listed under `devDependencies`, this may potentially cause issues in production builds.

### **Dependency Management and Readability**
- Dependencies were not clearly organized, making the `package.json` harder to maintain.

# Reengineering Task Overview
### **Updated `electron`  from `13.0.0` to `33.2.0`.**
- This is to make the project compatible with the latest Electron version, which includes performance improvements, security patches and new features)

### **Added node-gyp package (version `10.2.0`)** 
- This is for compiling native addons, which are used by Electron and other libraries in this project.

### **Added electron-rebuild under dependencies**
- This is to ensure compatibility in both development and production environments.

# Reengineering Approaches
**Dependency Management** – updated dependencies such as electron
**Structural Refinement** – Reordered and clarified the dependencies
**Infrastructure Enhancement** – Ensured support for native modules by adding `node-gyp`.

# Impact of Changes
### **Improved Compatibility**
- The Electron upgrade ensures the project is compatible with modern browsers and operating systems

### **Improved Build Stability**
- Adding `node-gyp` ensures that native modules compile correctly, reducing the likelihood of build failures

### CODE REVIEW

**Comment by suhadaudd11** [comment]
Very good. But it would be better if you share some snapshots of how the performance or security when the system uses old version vs new version of Electron

**Comment by abebeos** [comment]
@eefei22 , @ahmadileham , @ahmadileham 

This does not build, you can't change electron version, without doing some changes to the underlying code.

Can you please explain why you don't run the Github-Actions to test your PR's?

**Comment by Dexus** [comment]
@abebeos Well, you know. If you've got your hair mussed on me. With what they do here, you must have a bald head ;)

**Comment by abebeos** [comment]
> you must have a bald head

@Dexus , quite!  I must say that I'm really fraking out (after beeing happy when I saw code and descriptions, which looks like very solid work).

**Comment by abebeos** [comment]
Here an example of the real effort for an electron update (13 to 19 I think)

* https://github.com/deepnest-io/Deepnest/pull/188

**Pull request merged**
